name: pathSTR
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.9
  - cyvcf2=0.30.27
  - dash=2.18.2
  - dash-bio=1.0.2
  - dash-bootstrap-components=1.5.0
  - pandas=2.2.0
  - pyarrow>=15.0.0
  - dash-daq=0.5.0
  - rustworkx=0.14.2

